---
name: CI
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: git rev-parse HEAD
        run: git rev-parse HEAD
      - name: git branch
        run: git branch
      - name: git status
        run: git status
