---
name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - run: env
      - run: echo "$CTX"
        env:
          CTX: ${{toJSON(github)}}
